# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2
from . import streamsforge_pb2 as streamsforge__pb2

GRPC_GENERATED_VERSION = '1.83.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in streamsforge_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class SourceServiceStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.List = channel.unary_unary(
                '/streamsforge.v1.SourceService/List',
                request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
                response_deserializer=streamsforge__pb2.ListSourcesResponse.FromString,
                _registered_method=True)
        self.Get = channel.unary_unary(
                '/streamsforge.v1.SourceService/Get',
                request_serializer=streamsforge__pb2.GetSourceRequest.SerializeToString,
                response_deserializer=streamsforge__pb2.SourceDefinition.FromString,
                _registered_method=True)
        self.Create = channel.unary_unary(
                '/streamsforge.v1.SourceService/Create',
                request_serializer=streamsforge__pb2.SourceDefinition.SerializeToString,
                response_deserializer=streamsforge__pb2.SourceDefinition.FromString,
                _registered_method=True)
        self.Update = channel.unary_unary(
                '/streamsforge.v1.SourceService/Update',
                request_serializer=streamsforge__pb2.UpdateSourceRequest.SerializeToString,
                response_deserializer=streamsforge__pb2.SourceDefinition.FromString,
                _registered_method=True)
        self.Delete = channel.unary_unary(
                '/streamsforge.v1.SourceService/Delete',
                request_serializer=streamsforge__pb2.DeleteSourceRequest.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                _registered_method=True)


class SourceServiceServicer:
    """Missing associated documentation comment in .proto file."""

    def List(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Get(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Create(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Update(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Delete(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_SourceServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'List': grpc.unary_unary_rpc_method_handler(
                    servicer.List,
                    request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                    response_serializer=streamsforge__pb2.ListSourcesResponse.SerializeToString,
            ),
            'Get': grpc.unary_unary_rpc_method_handler(
                    servicer.Get,
                    request_deserializer=streamsforge__pb2.GetSourceRequest.FromString,
                    response_serializer=streamsforge__pb2.SourceDefinition.SerializeToString,
            ),
            'Create': grpc.unary_unary_rpc_method_handler(
                    servicer.Create,
                    request_deserializer=streamsforge__pb2.SourceDefinition.FromString,
                    response_serializer=streamsforge__pb2.SourceDefinition.SerializeToString,
            ),
            'Update': grpc.unary_unary_rpc_method_handler(
                    servicer.Update,
                    request_deserializer=streamsforge__pb2.UpdateSourceRequest.FromString,
                    response_serializer=streamsforge__pb2.SourceDefinition.SerializeToString,
            ),
            'Delete': grpc.unary_unary_rpc_method_handler(
                    servicer.Delete,
                    request_deserializer=streamsforge__pb2.DeleteSourceRequest.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'streamsforge.v1.SourceService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('streamsforge.v1.SourceService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class SourceService:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def List(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/streamsforge.v1.SourceService/List',
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            streamsforge__pb2.ListSourcesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Get(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/streamsforge.v1.SourceService/Get',
            streamsforge__pb2.GetSourceRequest.SerializeToString,
            streamsforge__pb2.SourceDefinition.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Create(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/streamsforge.v1.SourceService/Create',
            streamsforge__pb2.SourceDefinition.SerializeToString,
            streamsforge__pb2.SourceDefinition.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Update(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/streamsforge.v1.SourceService/Update',
            streamsforge__pb2.UpdateSourceRequest.SerializeToString,
            streamsforge__pb2.SourceDefinition.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Delete(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/streamsforge.v1.SourceService/Delete',
            streamsforge__pb2.DeleteSourceRequest.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class PipelineServiceStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.List = channel.unary_unary(
                '/streamsforge.v1.PipelineService/List',
                request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
                response_deserializer=streamsforge__pb2.ListPipelinesResponse.FromString,
                _registered_method=True)
        self.Get = channel.unary_unary(
                '/streamsforge.v1.PipelineService/Get',
                request_serializer=streamsforge__pb2.GetPipelineRequest.SerializeToString,
                response_deserializer=streamsforge__pb2.PipelineDefinition.FromString,
                _registered_method=True)
        self.Create = channel.unary_unary(
                '/streamsforge.v1.PipelineService/Create',
                request_serializer=streamsforge__pb2.CreatePipelineRequest.SerializeToString,
                response_deserializer=streamsforge__pb2.PipelineDefinition.FromString,
                _registered_method=True)
        self.Update = channel.unary_unary(
                '/streamsforge.v1.PipelineService/Update',
                request_serializer=streamsforge__pb2.UpdatePipelineRequest.SerializeToString,
                response_deserializer=streamsforge__pb2.PipelineDefinition.FromString,
                _registered_method=True)
        self.Delete = channel.unary_unary(
                '/streamsforge.v1.PipelineService/Delete',
                request_serializer=streamsforge__pb2.DeletePipelineRequest.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                _registered_method=True)
        self.Start = channel.unary_unary(
                '/streamsforge.v1.PipelineService/Start',
                request_serializer=streamsforge__pb2.StartPipelineRequest.SerializeToString,
                response_deserializer=streamsforge__pb2.PipelineDefinition.FromString,
                _registered_method=True)
        self.Stop = channel.unary_unary(
                '/streamsforge.v1.PipelineService/Stop',
                request_serializer=streamsforge__pb2.StopPipelineRequest.SerializeToString,
                response_deserializer=streamsforge__pb2.PipelineDefinition.FromString,
                _registered_method=True)
        self.Validate = channel.unary_unary(
                '/streamsforge.v1.PipelineService/Validate',
                request_serializer=streamsforge__pb2.ValidateRequest.SerializeToString,
                response_deserializer=streamsforge__pb2.ValidateResponse.FromString,
                _registered_method=True)


class PipelineServiceServicer:
    """Missing associated documentation comment in .proto file."""

    def List(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Get(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Create(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Update(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Delete(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Start(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Stop(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Validate(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_PipelineServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'List': grpc.unary_unary_rpc_method_handler(
                    servicer.List,
                    request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                    response_serializer=streamsforge__pb2.ListPipelinesResponse.SerializeToString,
            ),
            'Get': grpc.unary_unary_rpc_method_handler(
                    servicer.Get,
                    request_deserializer=streamsforge__pb2.GetPipelineRequest.FromString,
                    response_serializer=streamsforge__pb2.PipelineDefinition.SerializeToString,
            ),
            'Create': grpc.unary_unary_rpc_method_handler(
                    servicer.Create,
                    request_deserializer=streamsforge__pb2.CreatePipelineRequest.FromString,
                    response_serializer=streamsforge__pb2.PipelineDefinition.SerializeToString,
            ),
            'Update': grpc.unary_unary_rpc_method_handler(
                    servicer.Update,
                    request_deserializer=streamsforge__pb2.UpdatePipelineRequest.FromString,
                    response_serializer=streamsforge__pb2.PipelineDefinition.SerializeToString,
            ),
            'Delete': grpc.unary_unary_rpc_method_handler(
                    servicer.Delete,
                    request_deserializer=streamsforge__pb2.DeletePipelineRequest.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
            'Start': grpc.unary_unary_rpc_method_handler(
                    servicer.Start,
                    request_deserializer=streamsforge__pb2.StartPipelineRequest.FromString,
                    response_serializer=streamsforge__pb2.PipelineDefinition.SerializeToString,
            ),
            'Stop': grpc.unary_unary_rpc_method_handler(
                    servicer.Stop,
                    request_deserializer=streamsforge__pb2.StopPipelineRequest.FromString,
                    response_serializer=streamsforge__pb2.PipelineDefinition.SerializeToString,
            ),
            'Validate': grpc.unary_unary_rpc_method_handler(
                    servicer.Validate,
                    request_deserializer=streamsforge__pb2.ValidateRequest.FromString,
                    response_serializer=streamsforge__pb2.ValidateResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'streamsforge.v1.PipelineService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('streamsforge.v1.PipelineService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class PipelineService:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def List(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/streamsforge.v1.PipelineService/List',
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            streamsforge__pb2.ListPipelinesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Get(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/streamsforge.v1.PipelineService/Get',
            streamsforge__pb2.GetPipelineRequest.SerializeToString,
            streamsforge__pb2.PipelineDefinition.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Create(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/streamsforge.v1.PipelineService/Create',
            streamsforge__pb2.CreatePipelineRequest.SerializeToString,
            streamsforge__pb2.PipelineDefinition.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Update(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/streamsforge.v1.PipelineService/Update',
            streamsforge__pb2.UpdatePipelineRequest.SerializeToString,
            streamsforge__pb2.PipelineDefinition.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Delete(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/streamsforge.v1.PipelineService/Delete',
            streamsforge__pb2.DeletePipelineRequest.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Start(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/streamsforge.v1.PipelineService/Start',
            streamsforge__pb2.StartPipelineRequest.SerializeToString,
            streamsforge__pb2.PipelineDefinition.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Stop(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/streamsforge.v1.PipelineService/Stop',
            streamsforge__pb2.StopPipelineRequest.SerializeToString,
            streamsforge__pb2.PipelineDefinition.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Validate(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/streamsforge.v1.PipelineService/Validate',
            streamsforge__pb2.ValidateRequest.SerializeToString,
            streamsforge__pb2.ValidateResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class TableServiceStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.List = channel.unary_unary(
                '/streamsforge.v1.TableService/List',
                request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
                response_deserializer=streamsforge__pb2.ListTablesResponse.FromString,
                _registered_method=True)
        self.Get = channel.unary_unary(
                '/streamsforge.v1.TableService/Get',
                request_serializer=streamsforge__pb2.GetTableRequest.SerializeToString,
                response_deserializer=streamsforge__pb2.TableDefinition.FromString,
                _registered_method=True)
        self.Create = channel.unary_unary(
                '/streamsforge.v1.TableService/Create',
                request_serializer=streamsforge__pb2.CreateTableRequest.SerializeToString,
                response_deserializer=streamsforge__pb2.TableDefinition.FromString,
                _registered_method=True)
        self.Update = channel.unary_unary(
                '/streamsforge.v1.TableService/Update',
                request_serializer=streamsforge__pb2.UpdateTableRequest.SerializeToString,
                response_deserializer=streamsforge__pb2.TableDefinition.FromString,
                _registered_method=True)
        self.Delete = channel.unary_unary(
                '/streamsforge.v1.TableService/Delete',
                request_serializer=streamsforge__pb2.DeleteTableRequest.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                _registered_method=True)
        self.Start = channel.unary_unary(
                '/streamsforge.v1.TableService/Start',
                request_serializer=streamsforge__pb2.StartTableRequest.SerializeToString,
                response_deserializer=streamsforge__pb2.TableDefinition.FromString,
                _registered_method=True)
        self.Stop = channel.unary_unary(
                '/streamsforge.v1.TableService/Stop',
                request_serializer=streamsforge__pb2.StopTableRequest.SerializeToString,
                response_deserializer=streamsforge__pb2.TableDefinition.FromString,
                _registered_method=True)
        self.Validate = channel.unary_unary(
                '/streamsforge.v1.TableService/Validate',
                request_serializer=streamsforge__pb2.ValidateRequest.SerializeToString,
                response_deserializer=streamsforge__pb2.ValidateTableResponse.FromString,
                _registered_method=True)
        self.Rows = channel.unary_unary(
                '/streamsforge.v1.TableService/Rows',
                request_serializer=streamsforge__pb2.GetTableRowsRequest.SerializeToString,
                response_deserializer=streamsforge__pb2.TableRowsResponse.FromString,
                _registered_method=True)
        self.Search = channel.unary_unary(
                '/streamsforge.v1.TableService/Search',
                request_serializer=streamsforge__pb2.SearchTableRequest.SerializeToString,
                response_deserializer=streamsforge__pb2.SearchTableResponse.FromString,
                _registered_method=True)


class TableServiceServicer:
    """Missing associated documentation comment in .proto file."""

    def List(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Get(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Create(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Update(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Delete(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Start(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Stop(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Validate(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Rows(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Search(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_TableServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'List': grpc.unary_unary_rpc_method_handler(
                    servicer.List,
                    request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                    response_serializer=streamsforge__pb2.ListTablesResponse.SerializeToString,
            ),
            'Get': grpc.unary_unary_rpc_method_handler(
                    servicer.Get,
                    request_deserializer=streamsforge__pb2.GetTableRequest.FromString,
                    response_serializer=streamsforge__pb2.TableDefinition.SerializeToString,
            ),
            'Create': grpc.unary_unary_rpc_method_handler(
                    servicer.Create,
                    request_deserializer=streamsforge__pb2.CreateTableRequest.FromString,
                    response_serializer=streamsforge__pb2.TableDefinition.SerializeToString,
            ),
            'Update': grpc.unary_unary_rpc_method_handler(
                    servicer.Update,
                    request_deserializer=streamsforge__pb2.UpdateTableRequest.FromString,
                    response_serializer=streamsforge__pb2.TableDefinition.SerializeToString,
            ),
            'Delete': grpc.unary_unary_rpc_method_handler(
                    servicer.Delete,
                    request_deserializer=streamsforge__pb2.DeleteTableRequest.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
            'Start': grpc.unary_unary_rpc_method_handler(
                    servicer.Start,
                    request_deserializer=streamsforge__pb2.StartTableRequest.FromString,
                    response_serializer=streamsforge__pb2.TableDefinition.SerializeToString,
            ),
            'Stop': grpc.unary_unary_rpc_method_handler(
                    servicer.Stop,
                    request_deserializer=streamsforge__pb2.StopTableRequest.FromString,
                    response_serializer=streamsforge__pb2.TableDefinition.SerializeToString,
            ),
            'Validate': grpc.unary_unary_rpc_method_handler(
                    servicer.Validate,
                    request_deserializer=streamsforge__pb2.ValidateRequest.FromString,
                    response_serializer=streamsforge__pb2.ValidateTableResponse.SerializeToString,
            ),
            'Rows': grpc.unary_unary_rpc_method_handler(
                    servicer.Rows,
                    request_deserializer=streamsforge__pb2.GetTableRowsRequest.FromString,
                    response_serializer=streamsforge__pb2.TableRowsResponse.SerializeToString,
            ),
            'Search': grpc.unary_unary_rpc_method_handler(
                    servicer.Search,
                    request_deserializer=streamsforge__pb2.SearchTableRequest.FromString,
                    response_serializer=streamsforge__pb2.SearchTableResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'streamsforge.v1.TableService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('streamsforge.v1.TableService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class TableService:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def List(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/streamsforge.v1.TableService/List',
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            streamsforge__pb2.ListTablesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Get(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/streamsforge.v1.TableService/Get',
            streamsforge__pb2.GetTableRequest.SerializeToString,
            streamsforge__pb2.TableDefinition.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Create(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/streamsforge.v1.TableService/Create',
            streamsforge__pb2.CreateTableRequest.SerializeToString,
            streamsforge__pb2.TableDefinition.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Update(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/streamsforge.v1.TableService/Update',
            streamsforge__pb2.UpdateTableRequest.SerializeToString,
            streamsforge__pb2.TableDefinition.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Delete(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/streamsforge.v1.TableService/Delete',
            streamsforge__pb2.DeleteTableRequest.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Start(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/streamsforge.v1.TableService/Start',
            streamsforge__pb2.StartTableRequest.SerializeToString,
            streamsforge__pb2.TableDefinition.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Stop(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/streamsforge.v1.TableService/Stop',
            streamsforge__pb2.StopTableRequest.SerializeToString,
            streamsforge__pb2.TableDefinition.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Validate(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/streamsforge.v1.TableService/Validate',
            streamsforge__pb2.ValidateRequest.SerializeToString,
            streamsforge__pb2.ValidateTableResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Rows(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/streamsforge.v1.TableService/Rows',
            streamsforge__pb2.GetTableRowsRequest.SerializeToString,
            streamsforge__pb2.TableRowsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Search(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/streamsforge.v1.TableService/Search',
            streamsforge__pb2.SearchTableRequest.SerializeToString,
            streamsforge__pb2.SearchTableResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class StreamServiceStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SubscribeSource = channel.unary_stream(
                '/streamsforge.v1.StreamService/SubscribeSource',
                request_serializer=streamsforge__pb2.SubscribeSourceRequest.SerializeToString,
                response_deserializer=streamsforge__pb2.SourceEvent.FromString,
                _registered_method=True)
        self.SubscribePipeline = channel.unary_stream(
                '/streamsforge.v1.StreamService/SubscribePipeline',
                request_serializer=streamsforge__pb2.SubscribePipelineRequest.SerializeToString,
                response_deserializer=streamsforge__pb2.ResultEnvelope.FromString,
                _registered_method=True)
        self.SubscribeTable = channel.unary_stream(
                '/streamsforge.v1.StreamService/SubscribeTable',
                request_serializer=streamsforge__pb2.SubscribeTableRequest.SerializeToString,
                response_deserializer=streamsforge__pb2.TableDeltaBatch.FromString,
                _registered_method=True)


class StreamServiceServicer:
    """Missing associated documentation comment in .proto file."""

    def SubscribeSource(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SubscribePipeline(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SubscribeTable(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_StreamServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'SubscribeSource': grpc.unary_stream_rpc_method_handler(
                    servicer.SubscribeSource,
                    request_deserializer=streamsforge__pb2.SubscribeSourceRequest.FromString,
                    response_serializer=streamsforge__pb2.SourceEvent.SerializeToString,
            ),
            'SubscribePipeline': grpc.unary_stream_rpc_method_handler(
                    servicer.SubscribePipeline,
                    request_deserializer=streamsforge__pb2.SubscribePipelineRequest.FromString,
                    response_serializer=streamsforge__pb2.ResultEnvelope.SerializeToString,
            ),
            'SubscribeTable': grpc.unary_stream_rpc_method_handler(
                    servicer.SubscribeTable,
                    request_deserializer=streamsforge__pb2.SubscribeTableRequest.FromString,
                    response_serializer=streamsforge__pb2.TableDeltaBatch.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'streamsforge.v1.StreamService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('streamsforge.v1.StreamService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class StreamService:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def SubscribeSource(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/streamsforge.v1.StreamService/SubscribeSource',
            streamsforge__pb2.SubscribeSourceRequest.SerializeToString,
            streamsforge__pb2.SourceEvent.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SubscribePipeline(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/streamsforge.v1.StreamService/SubscribePipeline',
            streamsforge__pb2.SubscribePipelineRequest.SerializeToString,
            streamsforge__pb2.ResultEnvelope.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SubscribeTable(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/streamsforge.v1.StreamService/SubscribeTable',
            streamsforge__pb2.SubscribeTableRequest.SerializeToString,
            streamsforge__pb2.TableDeltaBatch.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class IngestServiceStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Ingest = channel.stream_stream(
                '/streamsforge.v1.IngestService/Ingest',
                request_serializer=streamsforge__pb2.IngestRequest.SerializeToString,
                response_deserializer=streamsforge__pb2.IngestAck.FromString,
                _registered_method=True)


class IngestServiceServicer:
    """Missing associated documentation comment in .proto file."""

    def Ingest(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_IngestServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Ingest': grpc.stream_stream_rpc_method_handler(
                    servicer.Ingest,
                    request_deserializer=streamsforge__pb2.IngestRequest.FromString,
                    response_serializer=streamsforge__pb2.IngestAck.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'streamsforge.v1.IngestService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('streamsforge.v1.IngestService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class IngestService:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Ingest(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(
            request_iterator,
            target,
            '/streamsforge.v1.IngestService/Ingest',
            streamsforge__pb2.IngestRequest.SerializeToString,
            streamsforge__pb2.IngestAck.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
