using Ycs;
using Xunit;

namespace StreamForge.Connectors.Crdt.Tests;

/// <summary>
/// Plan 020 wave A. This suite tests <em>the pin</em>, not the CRDT: Ycs has its own 274-test suite and
/// its own <c>interop/</c> harness that round-trips against the published Yjs packages, and duplicating
/// either here would be re-testing somebody else's library. What this repository actually needs to know
/// is two things a submodule bump can silently break:
///
/// <para>1. <b>That we are on the right branch.</b> <c>cotyar/ycs</c>'s <c>main</c> carries only the v2
/// update encoding and has neither <see cref="UpdateOperations"/> nor <c>PermanentUserData</c>. The
/// Yjs-13.6.32 parity work — v1 encoding, merge/diff/state-vector operations, snapshots, relative
/// positions, XML types, attribution — lives on <c>parity-yjs-13.6.32</c>. Wave C compacts its update
/// log with <see cref="UpdateOperations.MergeUpdates"/> and wave D reads
/// <see cref="UpdateOperations.DecodeUpdate"/> before merging; on <c>main</c> neither compiles. A
/// build error would be a fine way to learn that, but only if something references those members —
/// hence the explicit calls below.</para>
///
/// <para>2. <b>That it still reads bytes real Yjs produced.</b> The fixture is not ours: it was
/// generated by <c>interop/js/gen.mjs</c> against the published <c>yjs@13.6.32</c> package and is
/// pinned identically in the fork's own <c>YjsInteropTests</c>. Re-encoding byte-for-byte is
/// deliberately NOT asserted — Yjs makes no such guarantee across versions, and pinning it here would
/// turn a legal encoder change into a red suite. Convergence of the decoded document is the property
/// that matters and the one this asserts.</para>
/// </summary>
public class YcsPinTests
{
    // yjs 13.6.32, Y.encodeStateAsUpdate (v1). See the class doc for provenance.
    private const string Yjs13UpdateV1 =
        "ART60JjOBAAoAQNtYXADc3RyAXcQaGVsbG8g4pyTINC80LjRgCgBA21hcANpbnQBfSooAQNtYXAFZmxvYXQBfEBgAAAoAQNtYXAEYm9vbAF4KAEDbWFwBG51bGwBfigBA21hcARqc29uAXYCAWF9AQFidQJ3AXh3AXkjAQNtYXADYmluBAECA/onAQNtYXAGbmVzdGVkASgA+tCYzgQHBGRlZXABdwV2YWx1ZQgBBWFycmF5AXcBYYH60JjOBAkBiPrQmM4ECgJ5dgEBa3cBdof60JjOBAwACAD60JjOBA0CdwJpMHcCaTEEAQR0ZXh0BnBsYWluIIb60JjOBBUEYm9sZAR0cnVlhPrQmM4EFgRib2xkhvrQmM4EGgRib2xkBG51bGzE+tCYzgQa+tCYzgQbBSB0YWlshfrQmM4EGxF7ImltYWdlIjoieC5wbmcifQH60JjOBAEKAQ==";

    private static YDoc DocFromFixture()
    {
        var doc = new YDoc();
        doc.ApplyUpdateV1(Convert.FromBase64String(Yjs13UpdateV1));
        return doc;
    }

    [Fact]
    public void ReadsAV1UpdateProducedByRealYjs()
    {
        var map = DocFromFixture().GetMap("map");

        Assert.Equal("hello ✓ мир", map.Get("str"));
        Assert.Equal(42, Convert.ToInt32(map.Get("int")));
        Assert.Equal(true, map.Get("bool"));
        Assert.Equal(new byte[] { 1, 2, 3, 250 }, (byte[])map.Get("bin")!);
        // A nested Y-type, because the projector (wave B) has to flatten these and needs them to arrive.
        Assert.Equal("value", ((YMap)map.Get("nested")!).Get("deep"));
    }

    [Fact]
    public void ReEncodesToSomethingThatConvergesToTheSameDocument()
    {
        var reEncoded = DocFromFixture().EncodeStateAsUpdateV1();

        var target = new YDoc();
        target.ApplyUpdateV1(reEncoded);

        Assert.Equal("hello ✓ мир", target.GetMap("map").Get("str"));
        Assert.Equal("plain bold tail", target.GetText("text").ToString());
    }

    [Fact]
    public void IsPinnedToTheParityBranchThatCarriesTheUpdateOperationsWavesCAndDNeed()
    {
        // On `main` this method does not exist and this file does not compile — which is the assertion.
        // Merging an update with itself is the degenerate case on purpose: it needs no second document
        // and still fails loudly if the merge path is broken.
        var update = Convert.FromBase64String(Yjs13UpdateV1);
        var merged = UpdateOperations.MergeUpdates([update, update]);

        var doc = new YDoc();
        doc.ApplyUpdateV1(merged);
        Assert.Equal(42, Convert.ToInt32(doc.GetMap("map").Get("int")));

        // Wave D inspects what an update touches BEFORE merging it. Same reason: pin that it is here.
        Assert.NotEmpty(UpdateOperations.DecodeUpdate(update).Structs);
    }

    [Fact]
    public void ReApplyingTheSameUpdateChangesNothing()
    {
        // Plan 020 D7 — the property the whole store-and-forward design rests on: a flaky link that
        // redelivers the same batch four times costs four merges and zero downstream deltas. Asserted
        // against the pin now so that if it ever stops holding, it fails here and not in production.
        var update = Convert.FromBase64String(Yjs13UpdateV1);
        var doc = new YDoc();
        doc.ApplyUpdateV1(update);
        var afterFirst = doc.EncodeStateAsUpdateV1();

        doc.ApplyUpdateV1(update);
        doc.ApplyUpdateV1(update);

        Assert.Equal(afterFirst, doc.EncodeStateAsUpdateV1());
    }
}
