<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <LangVersion>latest</LangVersion>
  </PropertyGroup>
  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="10.0.*" />
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="10.0.10" />
    <PackageReference Include="Scalar.AspNetCore" Version="2.16.15" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\StreamForge.Engine\StreamForge.Engine.csproj" />
    <ProjectReference Include="..\StreamForge.Contracts\StreamForge.Contracts.csproj" />
    <ProjectReference Include="..\StreamForge.AppCore\StreamForge.AppCore.csproj" />
  </ItemGroup>
</Project>
