using System.Reflection;
using System.Text;

namespace StreamForge.Host.Grpc.Dynamic;

/// <summary>
/// Assembles the full, self-contained .proto file StreamForge hands out for download for one dynamic
/// entity (a source, pipeline, or table): a header banner, <see cref="DescriptorFactory"/>'s canonical
/// entity schema (<see cref="GeneratedSchema.ProtoText"/>), and — appended into the SAME file and
/// package — the <c>DynamicStreamService</c> streaming contract every dynamic entity is subscribed to
/// through. A client that compiles just this one file gets everything it needs: the typed
/// {Entity}/{Entity}Event/{Entity}Delta messages AND the RPC to subscribe to them.
///
/// <para>The appended block is written by hand (not generated from a descriptor) because
/// <c>EntitySubscribeRequest</c>/<c>DynamicFrame</c>/<c>DynamicStreamService</c> are fixed,
/// entity-independent declarations shared by every download — see the sibling
/// <c>DynamicStreamService</c>/<c>streamforge_dynamic.proto</c> implementation, which this text is kept
/// byte-for-byte in sync with. Validity of the combined file (no naming collisions, no import gaps,
/// well-formed proto3) is asserted by actually compiling it with protoc via Grpc.Tools in
/// ProtoFileBuilderCompileTests, not by inspection.</para>
/// </summary>
public static class ProtoFileBuilder
{
    /// <summary>Human-facing generator banner. Derived from this assembly's informational version so it
    /// tracks the running StreamForge build without needing a separately maintained constant.</summary>
    public static readonly string GeneratorVersion =
        Assembly.GetExecutingAssembly().GetCustomAttribute<AssemblyInformationalVersionAttribute>()?.InformationalVersion
        ?? Assembly.GetExecutingAssembly().GetName().Version?.ToString()
        ?? "dev";

    /// <summary>Builds the full downloadable .proto text for one entity.</summary>
    /// <param name="entityKind">"source" | "pipeline" | "table" — for the header comment only.</param>
    /// <param name="entityName">The entity's human-facing name (not its id), for the header comment only.</param>
    /// <param name="schema">The entity's generated schema from <see cref="DescriptorFactory.Generate"/>.</param>
    public static string Build(string entityKind, string entityName, GeneratedSchema schema)
    {
        ArgumentException.ThrowIfNullOrWhiteSpace(entityKind);
        ArgumentException.ThrowIfNullOrWhiteSpace(entityName);
        ArgumentNullException.ThrowIfNull(schema);

        var sb = new StringBuilder();

        // ---- Header banner --------------------------------------------------
        // Comments are permitted before the `syntax` statement in proto3; protoc treats them as
        // leading detached comments on the file, not as content that needs to follow syntax/package.
        sb.Append("// StreamForge generated .proto — do not edit by hand.\n");
        sb.Append("// Entity: ").Append(entityKind).Append(" \"").Append(entityName).Append("\"\n");
        sb.Append("// Generated by StreamForge ").Append(GeneratorVersion).Append('\n');
        sb.Append("// Self-contained: compiles standalone (protoc/Grpc.Tools) and includes the\n");
        sb.Append("// DynamicStreamService streaming contract needed to subscribe to this entity live.\n");
        sb.Append('\n');

        // ---- Entity schema (syntax + package + messages) --------------------
        // DescriptorFactory.RenderProtoText always ends its output with a single trailing '\n' after
        // the last message's closing brace (see ProtoTextTests' golden text) — never a blank line — so
        // exactly one blank-line separator is inserted below before the appended block.
        sb.Append(schema.ProtoText);
        sb.Append('\n');

        // ---- Streaming contract (fixed, entity-independent; shared by every download) ----
        sb.Append("// ---- Streaming contract (shared by every StreamForge dynamic entity) ----\n");
        sb.Append('\n');
        sb.Append("message EntitySubscribeRequest {\n");
        sb.Append("  string entity_key = 1;\n");
        sb.Append("}\n");
        sb.Append('\n');
        sb.Append("message DynamicFrame {\n");
        sb.Append("  string entity_key = 1;\n");
        sb.Append("  bytes payload = 2;\n");
        sb.Append("  int64 seq = 3;\n");
        sb.Append("}\n");
        sb.Append('\n');
        sb.Append("service DynamicStreamService {\n");
        sb.Append("  rpc SubscribeEntity(EntitySubscribeRequest) returns (stream DynamicFrame);\n");
        sb.Append("}\n");

        return sb.ToString();
    }
}
